name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: write-all

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Set up Java ☕️
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4

      - name: Build with Coverage
        run: mvn -file org.moreunit.build/pom.xml clean install -Pcoverage "-Dtarget.platform.classifier=eclipse-latest" --fail-at-end --batch-mode --strict-checksums --update-snapshots "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./org.moreunit.build/target/site/jacoco-aggregate/jacoco.xml
          verbose: true
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
