name: MoreUnit Build

on:
  push:
    branches: [ master ]
    tags : ['*']
  pull_request:
    branches: [ master ]

permissions: write-all

jobs:
  build:

    runs-on: windows-latest

    permissions:
      checks: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        
      - name: Set up Java ☕️
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5
        with:
          maven-version: 3.9.4

      - name: Build and verify
        run: mvn -file org.moreunit.build/pom.xml clean install "-Dtarget.platform.classifier=eclipse-latest" --fail-at-end --batch-mode --strict-checksums --update-snapshots "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

      - name: Publish Surefire Test Results for  🖨
        if: ${{ always() }}
        uses: ScaCap/action-surefire-report@v1
        with:
          check_name: test results

      - name: Flatten P2 repository
        uses: RoiSoleil/flatten-p2-repo@main
        with:
          repository-path: "./org.moreunit.updatesite/target/repository/"

      - name: Release SNAPSHOT
        if: github.ref == 'refs/heads/master'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "snapshot"
          prerelease: true
          title: "Development Build"
          files: |
            ./org.moreunit.updatesite/target/org.moreunit.updatesite-*-SNAPSHOT.zip
            ./org.moreunit.updatesite/target/flat-repository/*

      - name: Release RELEASE
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./org.moreunit.updatesite/target/org.moreunit.updatesite-*.zip
            ./org.moreunit.updatesite/target/flat-repository/*        
